CREATE DATABASE VENTAS_BAZAR;

USE VENTAS_BAZAR;

CREATE TABLE TIPO_CLIENTE(
	ID_TIPO_CLI INT AUTO_INCREMENT PRIMARY KEY,
	NOM_TIP_CLI VARCHAR(30)
);

CREATE TABLE TIPO_USUARIO(
	ID_TIPO_US INT AUTO_INCREMENT PRIMARY KEY,
	NOM_TIP_US VARCHAR(30)
);

CREATE TABLE CATEGORIAS(
	ID_CAT INT AUTO_INCREMENT PRIMARY KEY,
	NOM_CAT VARCHAR(30)
);

CREATE TABLE FACTURAS(
	ID_FAC INT AUTO_INCREMENT PRIMARY KEY,
	RUT_CLI_FAC VARCHAR(10),
	RAZ_CLI_FAC VARCHAR(30),
	GIRO_CLI_FAC VARCHAR(30),
	DIRE_CLI_FAC VARCHAR(100),
	COD_PRO_FAC INT,
	NOM_PRO_FAC VARCHAR(30),
	CAN_PRO_FAC INT,
	TOT_NET_FAC NUMERIC(10),
	IVA_PRO_FAC NUMERIC(10),
	TOT_PRO_FAC NUMERIC(10),
	TOT_FAC NUMERIC(10)
);

CREATE TABLE BOLETAS(
	ID_BOL INT AUTO_INCREMENT PRIMARY KEY,
	COD_PRO_BOL INT,
	NOM_PRO_BOL VARCHAR(30),
	CANT_PRO_BOL INT,
	TOT_NET_BOL NUMERIC(10),
	IVA_PRO_BOL NUMERIC(10),
	TOT_PRO_BOL NUMERIC(10),
	TOT_BOL NUMERIC(10)
);

CREATE TABLE HISTORIAL_LOGIN(
	ID_HIS_LOG INT AUTO_INCREMENT PRIMARY KEY,
	NOM_US_LOG VARCHAR(30),
	RUT_US_LOG VARCHAR(10),
	TIPO_US_LOG INT,
	FEC_LOG DATE,
	HOR_LOG TIME
);

CREATE TABLE CLIENTES(
	ID_RUT_CLI VARCHAR(10) PRIMARY KEY,
	NOM_CLI VARCHAR(30),
	DIR_CLI VARCHAR(100),
	TIP_CLI INT,
	FOREIGN KEY (TIP_CLI) REFERENCES TIPO_CLIENTE(ID_TIPO_CLI)
);

CREATE TABLE USUARIOS(
	ID_RUT_US VARCHAR(10) PRIMARY KEY,
	NOM_US VARCHAR(30),
	TIPO_US INT,
	USER_US VARCHAR(30),
	PASS_US VARCHAR(30),
	FOREIGN KEY (TIPO_US) REFERENCES TIPO_USUARIO(ID_TIPO_US)
);

CREATE TABLE PRODUCTOS(
	ID_PRO INT AUTO_INCREMENT PRIMARY KEY,
	COD_PRO INT,
	NOM_PRO VARCHAR(100),
	CAT_PRO INT,
	PRE_PRO NUMERIC(10),
	FOREIGN KEY (CAT_PRO) REFERENCES CATEGORIAS(ID_CAT)
);

CREATE TABLE VENTAS(
	ID_VEN INT AUTO_INCREMENT PRIMARY KEY,
	RUT_US_VEN VARCHAR(10),
	RUT_CLI_VEN VARCHAR(10),
	FEC_VEN DATE,
	HOR_VEN TIME,
	ID_FAC_VEN INT,
	ID_BOL_VEN INT,
	COD_PRO_VEN INT,
	NETO_PRO_VEN NUMERIC(10),
	IVA_PRO_VEN NUMERIC(10),
	TOT_PRO_VEN NUMERIC(10),
	CAN_PRO_VEN INT,
	TOT_VEN NUMERIC(10),
	FOREIGN KEY (RUT_US_VEN) REFERENCES USUARIOS(ID_RUT_US),
	FOREIGN KEY (RUT_CLI_VEN) REFERENCES CLIENTES(ID_RUT_CLI),
	FOREIGN KEY (ID_FAC_VEN) REFERENCES FACTURAS(ID_FAC),
	FOREIGN KEY (ID_BOL_VEN) REFERENCES BOLETAS(ID_BOL)
);

CREATE TABLE NUB_HISTORIAL_LOGIN_USUARIOS(
	HIS_US INT AUTO_INCREMENT PRIMARY KEY,
	HIS_LOG INT,
	RUT_US VARCHAR(10),
	FOREIGN KEY (HIS_LOG) REFERENCES HISTORIAL_LOGIN(ID_HIS_LOG),
	FOREIGN KEY (RUT_US) REFERENCES USUARIOS(ID_RUT_US)
);

CREATE TABLE NUB_VENTAS_PRODUCTOS(
	ID_VEN_PRO INT AUTO_INCREMENT PRIMARY KEY,
	ID_VEN INT,
	ID_PRO INT,
	FOREIGN KEY (ID_VEN) REFERENCES VENTAS(ID_VEN),
	FOREIGN KEY (ID_PRO) REFERENCES PRODUCTOS(ID_PRO)
);

CREATE TABLE EST_DIA(
	ID_EST_DIA INT AUTO_INCREMENT PRIMARY KEY,
	NOM_EST VARCHAR(50)
);

CREATE TABLE APERTURA_CIERRE(
	ID_APE_CIERR INT AUTO_INCREMENT PRIMARY KEY,
	ESTADO INT,
	FECHA DATE,
	HORA TIME,
	FOREIGN KEY (ESTADO) REFERENCES EST_DIA(ID_EST_DIA)
);